export const projectsData = [
    {

        img: 'project1.jpg',
        title: 'Kcal',
        info: 'Web application that allows users to input their calorie goal for the day, enter food items, select food from their food log.Users will select food from their personal food log and the appropriate amount will be subtracted from their calorie goal for the day.Pythons datetime handles the new instance of the user to have a new calorie goal daily. ',
        info2: 'Technologies used: Python, Django',
        url: 'https://k-cal.herokuapp.com/',
        repo: 'https://github.com/digeoesp/Kcal', // if no repo, the button will not show up
    },
    {

        img: 'project2.jpg',
        title: 'Meals on Wheel',
        info: 'A social app that allows members to upload their favorite food trucks and a description of what they enjoy eating; it also shares the city and name of food trucks for other members to check out. Members will have access to personal accounts where they can add and remove posts.',
        info2: 'Technologies used: Javascript, ExpressJS, Sequelize, PostgresQL, BCrypt, Cloudinary',
        url: 'https://meals-with-chill.herokuapp.com/',
        repo: 'https://github.com/digeoesp/Meals-on-wheels', // if no repo, the button will not show up
    },
    {

        img: 'project3.jpg',
        title: 'Tail Wag',
        info: 'Fullstack application where users are able to enter their zip code to search for dogs or cats that are currently available for adoption near their area. Utilizing PetFinder Api we are able to grab current and up to date data across the U.S and Canada',
        info2: 'Technologies used: React, CSS, Express, MongoDB, Mongoose',
        url: 'https://tail-wag.herokuapp.com',
        repo: 'https://github.com/digeoesp/mern-auth-frontend', // if no repo, the button will not show up
    },
    {

        img: 'project4.jpg',
        title: 'Number Guessing Game',
        info: 'A single player game against the computer. The player attempts to guess the random number generated by the computer within a certain amount of tries. Contains difficulty setting between hard and easy, Input field, Submit button; Displays correct or incorrect answer, and Displays if the guess is too high or low.',
        info2: 'Technologies used: HTML, CSS, JavaScript ',
        url: 'https://digeoesp.github.io/Number-Guessing-Game/',
        repo: 'https://github.com/digeoesp/Number-Guessing-Game', // if no repo, the button will not show up
    },
];
